[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lasso_11_2025"
version = "0.1.0"
description = "Lasso learning and rolling-window estimation"
authors = [{name = "Tommaso Di Francesco"}]
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["."]
